#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
COMPLETION_WAITING_DOTS="true"
zstyle ':completion:*' rehash true
if [ -d /usr/local/share/zsh/site-functions ]; then
  source /usr/local/share/zsh/site-functions/*
fi

if [ -r ~/.sh_aliases ]; then
  source ~/.sh_aliases
fi

